---
title: "CoV-2019"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(httr)
library(jsonlite)
library(tidyverse)
library(lubridate)
library(plotly)

raw_data <- GET('https://coronavirus-tracker-api.herokuapp.com/all') %>% .$content %>% rawToChar() %>% fromJSON(flatten = T)

prepare_data <- function(raw, type){
  tidy_data <- raw[[type]][['locations']] %>% select(country, contains('history')) %>% 
    as_tibble() %>% mutate_at(2:ncol(.), as.integer) %>%
    group_by(country) %>% summarise_all(.funs = sum) %>%
    rename_all(funs(gsub('history.', '', make.names(.)))) %>%
    pivot_longer(cols = colnames(.)[-1])
}

confirmed_cases <- prepare_data(raw_data, 'confirmed') %>% rename(date = name, 'confirmed' = value)
deaths <- prepare_data(raw_data, 'deaths') %>% rename(date = name, 'deaths' = value)
recovered <- prepare_data(raw_data, 'recovered') %>% rename(date = name, 'recovered' = value)

cov_complete_data <- left_join(confirmed_cases, deaths, by = c('country', 'date')) %>%
  left_join(recovered, by = c('country', 'date')) %>%
  mutate(date = mdy(date), active = confirmed - deaths - recovered)

countries <- as.list(unique(cov_complete_data[['country']]))
data_types <- as.list(colnames(cov_complete_data[3:ncol(cov_complete_data)]))
dates <- as.list(unique(cov_complete_data[['date']]))

#updateData <- reactive(
#  startData %>% group_by(!!! rlang::syms(input$GB)) %>% summarise_if(is.numeric,sum,na.rm=T))

updateCoVData <- reactive(
  cov_complete_data %>% filter(country = !!!rlang::sym(input$country))
)

```

Column {data-width=150}
-----------------------------------------------------------------------

### Chart A

```{r}
selectInput(inputId = 'country', label = 'Страна', choices = countries)
selectInput(inputId = 'metric', label = 'Показатель', choices = data_types)
dateRangeInput(inputId = 'dates', label = 'Даты', start = min(cov_complete_data[['date']]),
               min = min(cov_complete_data[['date']]),
               end = max(cov_complete_data[['date']]),
               max = max(cov_complete_data[['date']]),
               weekstart = 1,
               language = 'ru'
               )
```

Column {data-width=850}
-----------------------------------------------------------------------

### Chart B

```{r}
renderPlotly(ggplotly(ggplot(cov_complete_data, aes(x = date)) +
  geom_line(aes(y = active, colour = country))))
```

